"""Small UI/report localization helpers for the analysis app."""

from __future__ import annotations

from collections.abc import Iterable


Language = str


UI_TEXT: dict[str, dict[str, str]] = {
    "ro": {
        "window_title": "Analiza sanatatii plantelor",
        "language": "Limba",
        "romanian": "Romana",
        "english": "English",
        "sample": "Esantion",
        "load_sample_folder": "Incarca folder esantion",
        "load_image_file": "Incarca imagine/fisier",
        "configure_mixed_images": "Configurare / modifica imagini mixte",
        "wavelengths": "Lungimi de unda",
        "load_wavelength_csv": "Incarca CSV lungimi de unda",
        "output": "Iesire",
        "set_output_folder": "Seteaza folder iesire",
        "ndvi_threshold": "Prag NDVI",
        "spot_threshold": "Prag spot",
        "min_spot_area": "Arie minima spot",
        "texture_window": "Fereastra textura",
        "run_analysis": "Ruleaza analiza",
        "reload_outputs": "Reincarca iesirile",
        "summary": "Rezumat",
        "interpretation": "Interpretare",
        "camera_validation": "Validare camera",
        "alignment": "Aliniere",
        "spectra": "Spectre",
        "histogram": "Histograma",
        "indices": "Indici",
        "spot_table": "Tabel spoturi",
        "mask_spots": "Masca / spoturi",
        "text_report": "Raport text",
        "glossary": "Glosar",
        "json": "JSON",
        "spot_label": "eticheta",
        "area": "arie",
        "severity_rank": "rang severitate",
        "severity_score": "scor severitate",
        "centroid_x": "centroid x",
        "centroid_y": "centroid y",
        "bbox": "bbox",
        "delta_680_leaf": "delta 680 frunza",
        "delta_850_leaf": "delta 850 frunza",
        "background": "Fundal",
        "mode": "Mod",
        "opacity": "Opacitate",
        "background_680": "680 nm gri",
        "background_725": "725 nm gri",
        "background_850": "850 nm gri",
        "background_rgb": "RGB 650/556/532",
        "background_false_color": "Culoare falsa 850/725/680",
        "mode_outline": "Contur",
        "mode_filled": "Masca rosie umpluta",
        "mode_heatmap": "Harta termica",
        "mode_vegetation": "Vegetatie",
        "mode_background": "Doar imagine",
        "show_outlines": "Arata contururile",
        "show_labels": "Arata etichetele",
        "show_boxes": "Arata casetele",
        "show_suspicious_mask": "Arata masca spoturilor",
        "show_red_fill": "Arata umplerea rosie",
        "show_leaf_mask": "Arata masca frunzei",
        "refresh": "Actualizeaza",
        "export_current": "Exporta vizualizarea curenta",
        "export_all": "Exporta toate vizualizarile",
        "overlay_wait": "Ruleaza analiza pentru a afisa masca/spoturile.",
        "no_report": "Nu a fost gasit inca niciun raport:",
        "no_analysis_report": "Nu este incarcat niciun raport de analiza.",
        "no_alignment_preview": "Nu este disponibila nicio previzualizare de aliniere pentru imagini mixte.",
        "alignment_metadata": "Metadate aliniere",
        "overlay_reload_hint": "Ruleaza analiza sau reincarca un folder de iesire pentru a vedea suprapunerile suspecte.",
        "overlay_unavailable": "Suprapunerea nu este disponibila",
        "overlay_wording": "Suprapunere suspecta / candidati de zone afectate, nu un diagnostic.",
        "unknown_background": "Optiune de fundal necunoscuta",
        "saved_current_overlay": "A fost salvata suprapunerea suspecta curenta:",
        "export_failed": "Exportul a esuat",
        "saved_visualizations": "Vizualizari salvate:",
        "analysis_failed": "Analiza a esuat",
        "mixed_import": "Import mixt",
        "mixed_import_load_failed": (
            "Nu am putut incarca inputul curent ca specificatie editabila.\n"
            "Se va deschide configuratorul gol."
        ),
        "mixed_input_ready": "Input mixt pregatit",
        "mixed_input_saved": "Specificatia de intrare mixta a fost salvata/actualizata.\n\nRuleaza analiza si se va incarca:",
        "dialog_sample_folder": "Incarca folder esantion",
        "dialog_image_file": "Incarca imagine/fisier",
        "dialog_wavelength_csv": "Incarca CSV lungimi de unda",
        "dialog_output_folder": "Seteaza folder iesire",
        "supported_files": "Fisiere suportate",
        "mixed_specs": "Specificatii import mixt",
        "images": "Imagini",
        "all_files": "Toate fisierele",
        "csv_files": "Fisiere CSV",
    },
    "en": {
        "window_title": "Plant Health Analysis",
        "language": "Language",
        "romanian": "Romanian",
        "english": "English",
        "sample": "Sample",
        "load_sample_folder": "Load sample folder",
        "load_image_file": "Load image/file",
        "configure_mixed_images": "Configure / edit mixed images",
        "wavelengths": "Wavelengths",
        "load_wavelength_csv": "Load wavelength CSV",
        "output": "Output",
        "set_output_folder": "Set output folder",
        "ndvi_threshold": "NDVI threshold",
        "spot_threshold": "Spot threshold",
        "min_spot_area": "Minimum spot area",
        "texture_window": "Texture window",
        "run_analysis": "Run analysis",
        "reload_outputs": "Reload outputs",
        "summary": "Summary",
        "interpretation": "Interpretation",
        "camera_validation": "Camera validation",
        "alignment": "Alignment",
        "spectra": "Spectra",
        "histogram": "Histogram",
        "indices": "Indices",
        "spot_table": "Spot table",
        "mask_spots": "Mask / spots",
        "text_report": "Text report",
        "glossary": "Glossary",
        "json": "JSON",
        "spot_label": "label",
        "area": "area",
        "severity_rank": "severity rank",
        "severity_score": "severity score",
        "centroid_x": "centroid x",
        "centroid_y": "centroid y",
        "bbox": "bbox",
        "delta_680_leaf": "delta 680 leaf",
        "delta_850_leaf": "delta 850 leaf",
        "background": "Background",
        "mode": "Mode",
        "opacity": "Opacity",
        "background_680": "680 nm gray",
        "background_725": "725 nm gray",
        "background_850": "850 nm gray",
        "background_rgb": "RGB 650/556/532",
        "background_false_color": "False color 850/725/680",
        "mode_outline": "Outline",
        "mode_filled": "Filled red mask",
        "mode_heatmap": "Heatmap",
        "mode_vegetation": "Vegetation",
        "mode_background": "Image only",
        "show_outlines": "Show outlines",
        "show_labels": "Show labels",
        "show_boxes": "Show boxes",
        "show_suspicious_mask": "Show spot mask",
        "show_red_fill": "Show red fill",
        "show_leaf_mask": "Show leaf mask",
        "refresh": "Refresh",
        "export_current": "Export current view",
        "export_all": "Export all views",
        "overlay_wait": "Run analysis to display the mask/spots.",
        "no_report": "No report has been found yet:",
        "no_analysis_report": "No analysis report is loaded.",
        "no_alignment_preview": "No mixed-image alignment preview is available.",
        "alignment_metadata": "Alignment metadata",
        "overlay_reload_hint": "Run analysis or reload an output folder to see suspicious overlays.",
        "overlay_unavailable": "Overlay is not available",
        "overlay_wording": "Suspicious overlay / candidate affected areas, not a diagnosis.",
        "unknown_background": "Unknown background option",
        "saved_current_overlay": "Current suspicious overlay was saved:",
        "export_failed": "Export failed",
        "saved_visualizations": "Saved visualizations:",
        "analysis_failed": "Analysis failed",
        "mixed_import": "Mixed import",
        "mixed_import_load_failed": (
            "Could not load the current input as an editable specification.\n"
            "The empty configurator will open instead."
        ),
        "mixed_input_ready": "Mixed input ready",
        "mixed_input_saved": "The mixed-input specification was saved/updated.\n\nRun analysis and it will load:",
        "dialog_sample_folder": "Load sample folder",
        "dialog_image_file": "Load image/file",
        "dialog_wavelength_csv": "Load wavelength CSV",
        "dialog_output_folder": "Set output folder",
        "supported_files": "Supported files",
        "mixed_specs": "Mixed import specifications",
        "images": "Images",
        "all_files": "All files",
        "csv_files": "CSV files",
    },
}


REPORT_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("Rezumat determinist", "Deterministic summary"),
    ("Raport de analiza a sanatatii plantelor", "Plant health analysis report"),
    ("Eticheta determinista a anomaliei", "Deterministic anomaly label"),
    ("Eticheta anomaliei", "Anomaly label"),
    ("Nota: text bazat pe reguli din raportul JSON; fara diagnostic AI.", "Note: text based on rules from the JSON report; no AI diagnosis."),
    ("Nota: aceasta este o redare bazata pe reguli a raportului JSON, nu un diagnostic.", "Note: this is a rule-based rendering of the JSON report, not a diagnosis."),
    ("anomalie ridicata", "high anomaly"),
    ("anomalie moderata", "moderate anomaly"),
    ("anomalie redusa", "low anomaly"),
    ("Esantion", "Sample"),
    ("Adaptor", "Adapter"),
    ("Tip date analiza", "Analysis data type"),
    ("Tip date sursa", "Source data type"),
    ("Tip sursa", "Source type"),
    ("Date reale esantion", "Real sample data"),
    ("Date sintetice mock", "Mock synthetic data"),
    ("Pixeli de vegetatie", "Vegetation pixels"),
    ("Regiuni suspecte", "Suspect regions"),
    ("Regiunea", "Region"),
    ("Scor mediu spot", "Average spot score"),
    ("Scor maxim spot", "Maximum spot score"),
    ("Avertismente", "Warnings"),
    ("Atentionari", "Warnings"),
    ("Profil validare", "Validation profile"),
    ("r spectru", "spectrum r"),
    ("semnal afara/cutie", "outdoor/box signal"),
    ("Corectie camera", "Camera correction"),
    ("benzi corectate", "corrected bands"),
    ("Indici pe intreaga frunza", "Whole-leaf indices"),
    ("Interpretare relativa limitata, dar utilizabila, a indicilor.", "Limited but usable relative interpretation of the indices."),
    ("Interpretarea este limitata deoarece mai multi indici cheie nu sunt disponibili.", "Interpretation is limited because several key indices are not available."),
    ("Interpretarea este limitata deoarece unii indici cheie nu sunt disponibili.", "Interpretation is limited because some key indices are not available."),
    ("Interpretarea nu este disponibila pentru acest esantion.", "Interpretation is not available for this sample."),
    ("Interpretare", "Interpretation"),
    ("Stare generala", "General state"),
    ("Concluzie", "Conclusion"),
    ("Atentie", "Warning"),
    ("Motiv", "Reason"),
    ("lipseste banda necesara", "missing required band"),
    ("nu este disponibil pentru acest esantion", "is not available for this sample"),
    ("indisponibil pentru acest esantion", "unavailable for this sample"),
    ("indisponibil", "unavailable"),
    ("Sursa", "Source"),
    ("Numar", "Count"),
    ("Interval", "Range"),
    ("Profil tinta", "Target profile"),
    ("Tinte", "Targets"),
    ("Lungimi de unda disponibile", "Available wavelengths"),
    ("Lungimi de unda", "Wavelengths"),
    ("Calibrare aplicata", "Calibration applied"),
    ("Fisiere importate", "Imported files"),
    ("Roluri atribuite", "Assigned roles"),
    ("Aliniere", "Alignment"),
    ("Frunza intreaga", "Whole leaf"),
    ("Benzi medii", "Average bands"),
    ("Benzi corectate cu alb", "White-corrected bands"),
    ("Benzi compensate cu sursa", "Source-compensated bands"),
    ("Indici disponibili", "Available indices"),
    ("Indici indisponibili", "Unavailable indices"),
    ("Eticheta determinista", "Deterministic label"),
    ("Harti disponibile", "Available maps"),
    ("Harti de anomalie disponibile", "Available anomaly maps"),
    ("Parametri", "Parameters"),
    ("prag", "threshold"),
    ("arie minima", "minimum area"),
    ("morfologie", "morphology"),
    ("fereastra", "window"),
    ("Regiune selectata", "Selected region"),
    ("Eticheta", "Label"),
    ("Arie", "Area"),
    ("Rang severitate", "Severity rank"),
    ("Scor severitate", "Severity score"),
    ("Suspiciune medie", "Average suspiciousness"),
    ("Suspiciune maxima", "Maximum suspiciousness"),
    ("Centroid", "Centroid"),
    ("Delta banda frunza", "Leaf-band delta"),
    ("Nota detectie spoturi", "Spot detection note"),
    ("Ce inseamna pentru poza analizata", "What this means for the analyzed image"),
    ("Aplicatia analizeaza imaginea curenta, iar aceste numere arata cat de bine a fost validat sistemul camera/spectrometru pe datele reale.", "The app analyzes the current image, and these numbers show how well the camera/spectrometer system was validated on real data."),
    ("Perechi spectrale afara/in cutie", "Outdoor/box spectral pairs"),
    ("Similaritate mediana forma spectru", "Median spectral-shape similarity"),
    ("Raport semnal afara/in cutie", "Outdoor/box signal ratio"),
    ("Corelatie camera/spectrometru pe probe normalizate", "Camera/spectrometer correlation on normalized samples"),
    ("Cum se foloseste", "How to use it"),
    ("compara forme normalizate si rapoarte intre benzi, nu luminozitatea bruta singura", "compare normalized shapes and band ratios, not raw brightness alone"),
    ("pentru poze RGB simple, foloseste rezultatul ca masca/culoare, nu ca masurare NIR reala", "for simple RGB photos, use the result as a mask/color view, not as a real NIR measurement"),
    ("pentru dovada mai puternica, fotografiaza aceeasi frunza cu aceleasi filtre si aceeasi ordine", "for stronger evidence, photograph the same leaf with the same filters and the same order"),
    ("masuratorile din cutie si cele de afara trebuie calibrate separat", "box and outdoor measurements must be calibrated separately"),
    ("Nu exista benzi camera calibrate in raportul curent.", "There are no calibrated camera bands in the current report."),
    ("Valorile brute ale pozei sunt impartite la referinta alba a filtrului. Apoi aplicatia alege un model validat: regresie ridge multibanda cand trece testul leave-one-leaf-out, altfel un model single-band pentru lungimea de unda respectiva. Separat, curba masurata a sursei este folosita ca factor de compensare si ca greutate de incredere.", "The raw image values are divided by the filter white reference. Then the app chooses a validated model: multiband ridge regression when it passes the leave-one-leaf-out test, otherwise a single-band model for that wavelength. Separately, the measured source curve is used as a compensation factor and confidence weight."),
    ("brut", "raw"),
    ("corectat alb", "white-corrected"),
    ("compensat sursa", "source-compensated"),
    ("greutate", "weight"),
    ("echiv. spectrometru exclus low-confidence", "spectrometer equivalent excluded as low-confidence"),
    ("echiv. spectrometru", "spectrometer equivalent"),
    ("Indici calculati dupa estimarea spectrometrica validata", "Indices calculated after validated spectrometric estimation"),
    ("Indici exclusi din concluziile calibrate", "Indices excluded from calibrated conclusions"),
    ("Regresie multibanda", "Multiband regression"),
    ("folosita", "used"),
    ("nefolosita", "not used"),
    ("benzi observate", "observed bands"),
    ("Semnal vegetal general puternic.", "Strong overall vegetation signal."),
    ("Semnal vegetal general moderat spre puternic.", "Moderate to strong overall vegetation signal."),
    ("Semnal vegetal general slab.", "Weak overall vegetation signal."),
    ("Esantionul arata un semnal vegetal general puternic.", "The sample shows a strong overall vegetation signal."),
    ("Esantionul arata un semnal vegetal puternic bazat pe NDVI.", "The sample shows a strong vegetation signal based on NDVI."),
    ("Esantionul arata un semnal vegetal moderat spre util.", "The sample shows a moderate to useful vegetation signal."),
    ("Esantionul arata un semnal vegetal slab in indicii disponibili.", "The sample shows a weak vegetation signal in the available indices."),
    ("Indicatorii sensibili la red-edge sunt mai moderati decat semnalul vegetal general.", "The red-edge-sensitive indicators are more moderate than the general vegetation signal."),
    ("Semnalul sensibil la red-edge este modest si trebuie interpretat comparativ.", "The red-edge-sensitive signal is modest and should be interpreted comparatively."),
    ("Semnalul legat de apa este relativ redus in aceasta masurare.", "The water-related signal is relatively low in this measurement."),
    ("Semnalul legat de apa este moderat in aceasta masurare.", "The water-related signal is moderate in this measurement."),
    ("Semnalul legat de apa este mai puternic in aceasta masurare.", "The water-related signal is stronger in this measurement."),
    ("Indicii disponibili ofera un semnal relativ, dar nu suficiente dovezi pentru o concluzie puternica.", "The available indices provide a relative signal, but not enough evidence for a strong conclusion."),
    ("Aceste rezultate pot reflecta variatie normala intre esantioane sau diferente fiziologice subtile si ar trebui comparate intre probe.", "These results may reflect normal variation between samples or subtle physiological differences and should be compared across samples."),
    ("Acestea sunt interpretari relative deterministe ale unor masurari de aproape. Nu reprezinta un diagnostic de boala, seceta sau deficienta de nutrienti.", "These are deterministic relative interpretations of close-range measurements. They do not represent a diagnosis of disease, drought, or nutrient deficiency."),
    ("Trataza-l ca pe un indicator aproximativ, nu ca pe o masurare directa a continutului de apa din frunza.", "Treat it as an approximate indicator, not as a direct measurement of leaf water content."),
    ("Acest rezultat trebuie interpretat comparativ, nu ca un diagnostic de sine statator.", "This result should be interpreted comparatively, not as a stand-alone diagnosis."),
    ("Este cel mai util pentru comparatie relativa intre esantioane.", "It is most useful for relative comparison between samples."),
    ("Valoarea NDVI sugereaza absenta vegetatiei sau un semnal de vegetatie nevalid.", "The NDVI value suggests no vegetation or an invalid vegetation signal."),
    ("Valoarea NDVI sugereaza un semnal vegetal general slab sau o structura foliara activa limitata.", "The NDVI value suggests a weak overall vegetation signal or limited active leaf structure."),
    ("Valoarea NDVI sugereaza o activitate vegetala moderata.", "The NDVI value suggests moderate vegetation activity."),
    ("Valoarea NDVI sugereaza o activitate vegetala generala puternica si un semnal clar de frunza.", "The NDVI value suggests strong overall vegetation activity and a clear leaf signal."),
    ("Valoarea NDRE indica un raspuns red-edge foarte slab, care poate reflecta un semnal red-edge limitat.", "The NDRE value indicates a very weak red-edge response, which may reflect a limited red-edge signal."),
    ("Valoarea NDRE indica un raspuns red-edge relativ slab, care poate reflecta diferente in semnalul legat de clorofila sau un raspuns subtil de stres.", "The NDRE value indicates a relatively weak red-edge response, which may reflect differences in the chlorophyll-related signal or a subtle stress response."),
    ("Valoarea NDRE indica un raspuns red-edge mai puternic, compatibil cu un semnal vegetal red-edge mai pronuntat.", "The NDRE value indicates a stronger red-edge response, compatible with a more pronounced red-edge vegetation signal."),
    ("Valoarea GNDVI sugereaza un semnal vegetal slab sau nevalid pentru aceasta configuratie.", "The GNDVI value suggests a weak or invalid vegetation signal for this configuration."),
    ("Valoarea GNDVI sugereaza un raspuns vegetativ verde-NIR redus in raport cu aceasta configuratie de masurare.", "The GNDVI value suggests a reduced green-NIR vegetation response for this measurement configuration."),
    ("Valoarea GNDVI sugereaza un raspuns verde-NIR mai puternic si un semnal activ de frunza in raport cu aceasta configuratie de masurare.", "The GNDVI value suggests a stronger green-NIR response and active leaf signal for this measurement configuration."),
    ("Valoarea CI_RE sugereaza un semnal red-edge legat de clorofila foarte redus.", "The CI_RE value suggests a very low chlorophyll-related red-edge signal."),
    ("Valoarea CI_RE sugereaza un semnal red-edge legat de clorofila redus pana la moderat.", "The CI_RE value suggests a low to moderate chlorophyll-related red-edge signal."),
    ("Valoarea CI_RE sugereaza un semnal red-edge legat de clorofila mai puternic.", "The CI_RE value suggests a stronger chlorophyll-related red-edge signal."),
    ("Valoarea proxy pentru apa sugereaza un semnal relativ redus legat de apa in aceasta masurare.", "The water proxy value suggests a relatively low water-related signal in this measurement."),
    ("Valoarea proxy pentru apa sugereaza un semnal relativ moderat legat de apa in aceasta masurare.", "The water proxy value suggests a relatively moderate water-related signal in this measurement."),
    ("Valoarea proxy pentru apa sugereaza un semnal relativ mai puternic legat de apa in aceasta masurare.", "The water proxy value suggests a relatively stronger water-related signal in this measurement."),
    ("Proxy de apa", "Water proxy"),
)


def tr(key: str, language: Language = "ro") -> str:
    """Return a UI string for the requested language."""

    table = UI_TEXT.get(language, UI_TEXT["ro"])
    return table.get(key, UI_TEXT["ro"].get(key, key))


def translate_report_text(text: str, language: Language = "ro") -> str:
    """Translate deterministic Romanian report prose to English for display."""

    if language != "en" or not text:
        return text
    translated = text
    for source, target in REPORT_REPLACEMENTS:
        translated = translated.replace(source, target)
    return translated


def combo_entries(entries: Iterable[tuple[str, str]], language: Language) -> list[tuple[str, str]]:
    """Build display/data entries for a localized combo box."""

    return [(tr(text_key, language), value) for text_key, value in entries]
